export const FAILING_TESTS = new Set([
  "clauses/create > Create1 - Creating nodes|8",
  "clauses/create > Create1 - Creating nodes|10",
  "clauses/create > Create1 - Creating nodes|11",
  "clauses/create > Create1 - Creating nodes|12",
  "clauses/create > Create2 - Creating relationships|14",
  "clauses/create > Create2 - Creating relationships|16",
  "clauses/create > Create2 - Creating relationships|17",
  "clauses/delete > Delete4 - Delete clause interoperation with other clauses|1",
  "clauses/delete > Delete4 - Delete clause interoperation with other clauses|2",
  "clauses/delete > Delete5 - Delete clause interoperation with built-in data types|1",
  "clauses/delete > Delete5 - Delete clause interoperation with built-in data types|2",
  "clauses/delete > Delete5 - Delete clause interoperation with built-in data types|3",
  "clauses/delete > Delete5 - Delete clause interoperation with built-in data types|4",
  "clauses/delete > Delete5 - Delete clause interoperation with built-in data types|5",
  "clauses/delete > Delete5 - Delete clause interoperation with built-in data types|6",
  "clauses/delete > Delete5 - Delete clause interoperation with built-in data types|7",
  "clauses/delete > Delete6 - Persistence of delete clause side effects|1",
  "clauses/delete > Delete6 - Persistence of delete clause side effects|2",
  "clauses/delete > Delete6 - Persistence of delete clause side effects|3",
  "clauses/delete > Delete6 - Persistence of delete clause side effects|4",
  "clauses/delete > Delete6 - Persistence of delete clause side effects|5",
  "clauses/delete > Delete6 - Persistence of delete clause side effects|6",
  "clauses/delete > Delete6 - Persistence of delete clause side effects|7",
  "clauses/delete > Delete6 - Persistence of delete clause side effects|8",
  "clauses/delete > Delete6 - Persistence of delete clause side effects|9",
  "clauses/delete > Delete6 - Persistence of delete clause side effects|10",
  "clauses/delete > Delete6 - Persistence of delete clause side effects|11",
  "clauses/delete > Delete6 - Persistence of delete clause side effects|12",
  "clauses/delete > Delete6 - Persistence of delete clause side effects|13",
  "clauses/delete > Delete6 - Persistence of delete clause side effects|14",
  "clauses/create > Create3 - Interoperation with other clauses|5",
  "clauses/create > Create3 - Interoperation with other clauses|6",
  "clauses/create > Create3 - Interoperation with other clauses|7",
  "clauses/create > Create3 - Interoperation with other clauses|8",
  "clauses/create > Create3 - Interoperation with other clauses|12",
  "clauses/create > Create6 - Persistence of create clause side effects|1",
  "clauses/create > Create6 - Persistence of create clause side effects|10",
  "clauses/create > Create6 - Persistence of create clause side effects|11",
  "clauses/create > Create6 - Persistence of create clause side effects|12",
  "clauses/create > Create6 - Persistence of create clause side effects|13",
  "clauses/create > Create6 - Persistence of create clause side effects|14",
  "clauses/create > Create6 - Persistence of create clause side effects|2",
  "clauses/create > Create6 - Persistence of create clause side effects|3",
  "clauses/create > Create6 - Persistence of create clause side effects|4",
  "clauses/create > Create6 - Persistence of create clause side effects|5",
  "clauses/create > Create6 - Persistence of create clause side effects|6",
  "clauses/create > Create6 - Persistence of create clause side effects|7",
  "clauses/create > Create6 - Persistence of create clause side effects|8",
  "clauses/create > Create6 - Persistence of create clause side effects|9",




  "clauses/match > Match3 - Match fixed length patterns|8",
  "clauses/match > Match3 - Match fixed length patterns|15",
  "clauses/match > Match3 - Match fixed length patterns|16",
  "clauses/match > Match3 - Match fixed length patterns|17",
  "clauses/match > Match3 - Match fixed length patterns|18",
  "clauses/match > Match3 - Match fixed length patterns|22",
  "clauses/match > Match3 - Match fixed length patterns|25",
  "clauses/match > Match3 - Match fixed length patterns|28",
  "clauses/match > Match4 - Match variable length patterns scenarios|1",
  "clauses/match > Match4 - Match variable length patterns scenarios|3",
  "clauses/match > Match4 - Match variable length patterns scenarios|4",
  "clauses/match > Match4 - Match variable length patterns scenarios|5",
  "clauses/match > Match4 - Match variable length patterns scenarios|6",
  "clauses/match > Match4 - Match variable length patterns scenarios|7",
  "clauses/match > Match4 - Match variable length patterns scenarios|8",
  "clauses/match > Match5 - Match variable length patterns over given graphs scenarios|1",
  "clauses/match > Match5 - Match variable length patterns over given graphs scenarios|10",
  "clauses/match > Match5 - Match variable length patterns over given graphs scenarios|14",
  "clauses/match > Match5 - Match variable length patterns over given graphs scenarios|15",
  "clauses/match > Match5 - Match variable length patterns over given graphs scenarios|16",
  "clauses/match > Match5 - Match variable length patterns over given graphs scenarios|17",
  "clauses/match > Match5 - Match variable length patterns over given graphs scenarios|18",
  "clauses/match > Match5 - Match variable length patterns over given graphs scenarios|19",
  "clauses/match > Match5 - Match variable length patterns over given graphs scenarios|2",
  "clauses/match > Match5 - Match variable length patterns over given graphs scenarios|20",
  "clauses/match > Match5 - Match variable length patterns over given graphs scenarios|21",
  "clauses/match > Match5 - Match variable length patterns over given graphs scenarios|22",
  "clauses/match > Match5 - Match variable length patterns over given graphs scenarios|23",
  "clauses/match > Match5 - Match variable length patterns over given graphs scenarios|24",
  "clauses/match > Match5 - Match variable length patterns over given graphs scenarios|25",
  "clauses/match > Match5 - Match variable length patterns over given graphs scenarios|26",
  "clauses/match > Match5 - Match variable length patterns over given graphs scenarios|27",
  "clauses/match > Match5 - Match variable length patterns over given graphs scenarios|28",
  "clauses/match > Match5 - Match variable length patterns over given graphs scenarios|29",
  "clauses/match > Match5 - Match variable length patterns over given graphs scenarios|3",
  "clauses/match > Match5 - Match variable length patterns over given graphs scenarios|4",
  "clauses/match > Match5 - Match variable length patterns over given graphs scenarios|5",
  "clauses/match > Match5 - Match variable length patterns over given graphs scenarios|6",
  "clauses/match > Match5 - Match variable length patterns over given graphs scenarios|7",
  "clauses/match > Match5 - Match variable length patterns over given graphs scenarios|8",
  "clauses/match > Match5 - Match variable length patterns over given graphs scenarios|9",
  "clauses/match > Match6 - Match named paths scenarios|1",
  "clauses/match > Match6 - Match named paths scenarios|10",
  "clauses/match > Match6 - Match named paths scenarios|11",
  "clauses/match > Match6 - Match named paths scenarios|12",
  "clauses/match > Match6 - Match named paths scenarios|13",
  "clauses/match > Match6 - Match named paths scenarios|14",
  "clauses/match > Match6 - Match named paths scenarios|15",
  "clauses/match > Match6 - Match named paths scenarios|16",
  "clauses/match > Match6 - Match named paths scenarios|17",
  "clauses/match > Match6 - Match named paths scenarios|18",
  "clauses/match > Match6 - Match named paths scenarios|19",
  "clauses/match > Match6 - Match named paths scenarios|2",
  "clauses/match > Match6 - Match named paths scenarios|20",
  "clauses/match > Match6 - Match named paths scenarios|3",
  "clauses/match > Match6 - Match named paths scenarios|5",
  "clauses/match > Match6 - Match named paths scenarios|6",
  "clauses/match > Match6 - Match named paths scenarios|7",
  "clauses/match > Match6 - Match named paths scenarios|9",
  "clauses/match > Match7 - Optional match|10",
  "clauses/match > Match7 - Optional match|11",
  "clauses/match > Match7 - Optional match|12",
  "clauses/match > Match7 - Optional match|14",
  "clauses/match > Match7 - Optional match|15",
  "clauses/match > Match7 - Optional match|16",
  "clauses/match > Match7 - Optional match|17",
  "clauses/match > Match7 - Optional match|18",
  "clauses/match > Match7 - Optional match|19",
  "clauses/match > Match7 - Optional match|20",
  "clauses/match > Match7 - Optional match|21",
  "clauses/match > Match7 - Optional match|22",
  "clauses/match > Match7 - Optional match|24",
  "clauses/match > Match7 - Optional match|25",
  "clauses/match > Match7 - Optional match|28",
  "clauses/match > Match7 - Optional match|29",
  "clauses/match > Match7 - Optional match|3",
  "clauses/match > Match7 - Optional match|30",
  "clauses/match > Match7 - Optional match|31",
  "clauses/match > Match7 - Optional match|4",
  "clauses/match > Match7 - Optional match|5",
  "clauses/match > Match7 - Optional match|6",
  "clauses/match > Match7 - Optional match|8",
  "clauses/match > Match7 - Optional match|9",
  "clauses/match > Match8 - Match clause interoperation with other clauses|2",
  "clauses/match > Match8 - Match clause interoperation with other clauses|3",
  "clauses/match > Match9 - Match deprecated scenarios|1",
  "clauses/match > Match9 - Match deprecated scenarios|2",
  "clauses/match > Match9 - Match deprecated scenarios|3",
  "clauses/match > Match9 - Match deprecated scenarios|4",
  "clauses/match > Match9 - Match deprecated scenarios|5",
  "clauses/match > Match9 - Match deprecated scenarios|8",
  "clauses/match > Match9 - Match deprecated scenarios|9",
  "clauses/merge > Merge1 - Merge node|1",
  "clauses/merge > Merge1 - Merge node|10",
  "clauses/merge > Merge1 - Merge node|11",
  "clauses/merge > Merge1 - Merge node|12",
  "clauses/merge > Merge1 - Merge node|13",
  "clauses/merge > Merge1 - Merge node|14",
  "clauses/merge > Merge1 - Merge node|2",
  "clauses/merge > Merge1 - Merge node|3",
  "clauses/merge > Merge1 - Merge node|4",
  "clauses/merge > Merge1 - Merge node|5",
  "clauses/merge > Merge1 - Merge node|6",
  "clauses/merge > Merge1 - Merge node|7",
  "clauses/merge > Merge1 - Merge node|8",
  "clauses/merge > Merge1 - Merge node|9",
  "clauses/merge > Merge2 - Merge node - on create|1",
  "clauses/merge > Merge2 - Merge node - on create|2",
  "clauses/merge > Merge2 - Merge node - on create|3",
  "clauses/merge > Merge2 - Merge node - on create|5",
  "clauses/merge > Merge3 - Merge node - on match|1",
  "clauses/merge > Merge3 - Merge node - on match|2",
  "clauses/merge > Merge3 - Merge node - on match|3",
  "clauses/merge > Merge3 - Merge node - on match|4",
  "clauses/merge > Merge4 - Merge node - on match and on create|1",
  "clauses/merge > Merge4 - Merge node - on match and on create|2",
  "clauses/merge > Merge5 - Merge relationships|1",
  "clauses/merge > Merge5 - Merge relationships|10",
  "clauses/merge > Merge5 - Merge relationships|11",
  "clauses/merge > Merge5 - Merge relationships|12",
  "clauses/merge > Merge5 - Merge relationships|13",
  "clauses/merge > Merge5 - Merge relationships|14",
  "clauses/merge > Merge5 - Merge relationships|15",
  "clauses/merge > Merge5 - Merge relationships|16",
  "clauses/merge > Merge5 - Merge relationships|17",
  "clauses/merge > Merge5 - Merge relationships|18",
  "clauses/merge > Merge5 - Merge relationships|19",
  "clauses/merge > Merge5 - Merge relationships|2",
  "clauses/merge > Merge5 - Merge relationships|20",
  "clauses/merge > Merge5 - Merge relationships|21",
  "clauses/merge > Merge5 - Merge relationships|29",
  "clauses/merge > Merge5 - Merge relationships|3",
  "clauses/merge > Merge5 - Merge relationships|4",
  "clauses/merge > Merge5 - Merge relationships|5",
  "clauses/merge > Merge5 - Merge relationships|6",
  "clauses/merge > Merge5 - Merge relationships|7",
  "clauses/merge > Merge5 - Merge relationships|8",
  "clauses/merge > Merge6 - Merge relationships - on create|1",
  "clauses/merge > Merge6 - Merge relationships - on create|2",
  "clauses/merge > Merge6 - Merge relationships - on create|3",
  "clauses/merge > Merge6 - Merge relationships - on create|4",
  "clauses/merge > Merge6 - Merge relationships - on create|5",
  "clauses/merge > Merge6 - Merge relationships - on create|6",
  "clauses/merge > Merge7 - Merge relationships - on match|3",
  "clauses/merge > Merge7 - Merge relationships - on match|4",
  "clauses/merge > Merge7 - Merge relationships - on match|5",
  "clauses/merge > Merge8 - Merge relationships - on match and on create|1",
  "clauses/merge > Merge9 - Merge clause interoperation with other clauses|1",
  "clauses/merge > Merge9 - Merge clause interoperation with other clauses|2",
  "clauses/merge > Merge9 - Merge clause interoperation with other clauses|3",
  "clauses/merge > Merge9 - Merge clause interoperation with other clauses|4",
  "clauses/return > Return2 - Return single expression (correctly projecting an expression)|1",
  "clauses/return > Return2 - Return single expression (correctly projecting an expression)|10",
  "clauses/return > Return2 - Return single expression (correctly projecting an expression)|11",
  "clauses/return > Return2 - Return single expression (correctly projecting an expression)|12",
  "clauses/return > Return2 - Return single expression (correctly projecting an expression)|13",
  "clauses/return > Return2 - Return single expression (correctly projecting an expression)|14",
  "clauses/return > Return2 - Return single expression (correctly projecting an expression)|2",
  "clauses/return > Return2 - Return single expression (correctly projecting an expression)|4",
  "clauses/return > Return2 - Return single expression (correctly projecting an expression)|7",

  "clauses/return > Return2 - Return single expression (correctly projecting an expression)|9",

  "clauses/return > Return3 - Return multiple expressions (if column order correct)|2",
  "clauses/return > Return3 - Return multiple expressions (if column order correct)|3",

  "clauses/return > Return4 - Column renaming|4",
  "clauses/return > Return4 - Column renaming|6",
  "clauses/return > Return4 - Column renaming|8",
  "clauses/return > Return4 - Column renaming|9",
  "clauses/return > Return4 - Column renaming|11",

  "clauses/return > Return5 - Implicit grouping with distinct|4",
  "clauses/return > Return5 - Implicit grouping with distinct|5",
  "clauses/return > Return6 - Implicit grouping with aggregates|2",
  "clauses/return > Return6 - Implicit grouping with aggregates|3",
  "clauses/return > Return6 - Implicit grouping with aggregates|4",
  "clauses/return > Return6 - Implicit grouping with aggregates|5",
  "clauses/return > Return6 - Implicit grouping with aggregates|6",
  "clauses/return > Return6 - Implicit grouping with aggregates|7",
  "clauses/return > Return6 - Implicit grouping with aggregates|8",
  "clauses/return > Return6 - Implicit grouping with aggregates|10",
  "clauses/return > Return6 - Implicit grouping with aggregates|11",
  "clauses/return > Return6 - Implicit grouping with aggregates|12",
  "clauses/return > Return6 - Implicit grouping with aggregates|13",
  "clauses/return > Return6 - Implicit grouping with aggregates|16",
  "clauses/return > Return6 - Implicit grouping with aggregates|18",
  "clauses/return > Return7 - Return all variables|1",
  "clauses/return > Return8 - Return clause interoperation with other clauses|1",
  "clauses/set > Set1 - Set a Property|1",
  "clauses/set > Set1 - Set a Property|10",
  "clauses/set > Set1 - Set a Property|11",
  "clauses/set > Set1 - Set a Property|2",
  "clauses/set > Set1 - Set a Property|3",
  "clauses/set > Set1 - Set a Property|4",
  "clauses/set > Set1 - Set a Property|5",
  "clauses/set > Set1 - Set a Property|6",
  "clauses/set > Set1 - Set a Property|7",
  "clauses/set > Set2 - Set a Property to Null|1",
  "clauses/set > Set2 - Set a Property to Null|2",
  "clauses/set > Set2 - Set a Property to Null|3",
  "clauses/set > Set3 - Set a Label|1",
  "clauses/set > Set3 - Set a Label|2",
  "clauses/set > Set3 - Set a Label|3",
  "clauses/set > Set3 - Set a Label|4",
  "clauses/set > Set3 - Set a Label|5",
  "clauses/set > Set3 - Set a Label|6",
  "clauses/set > Set3 - Set a Label|7",
  "clauses/set > Set4 - Set all properties with a map|1",
  "clauses/set > Set4 - Set all properties with a map|2",
  "clauses/set > Set4 - Set all properties with a map|3",
  "clauses/set > Set4 - Set all properties with a map|4",
  "clauses/set > Set5 - Set multiple properties with a map|2",
  "clauses/set > Set5 - Set multiple properties with a map|3",
  "clauses/set > Set5 - Set multiple properties with a map|4",
  "clauses/set > Set6 - Persistence of set clause side effects|1",
  "clauses/set > Set6 - Persistence of set clause side effects|10",
  "clauses/set > Set6 - Persistence of set clause side effects|11",
  "clauses/set > Set6 - Persistence of set clause side effects|12",
  "clauses/set > Set6 - Persistence of set clause side effects|13",
  "clauses/set > Set6 - Persistence of set clause side effects|14",
  "clauses/set > Set6 - Persistence of set clause side effects|15",
  "clauses/set > Set6 - Persistence of set clause side effects|16",
  "clauses/set > Set6 - Persistence of set clause side effects|17",
  "clauses/set > Set6 - Persistence of set clause side effects|18",
  "clauses/set > Set6 - Persistence of set clause side effects|19",
  "clauses/set > Set6 - Persistence of set clause side effects|2",
  "clauses/set > Set6 - Persistence of set clause side effects|20",
  "clauses/set > Set6 - Persistence of set clause side effects|21",
  "clauses/set > Set6 - Persistence of set clause side effects|3",
  "clauses/set > Set6 - Persistence of set clause side effects|4",
  "clauses/set > Set6 - Persistence of set clause side effects|5",
  "clauses/set > Set6 - Persistence of set clause side effects|6",
  "clauses/set > Set6 - Persistence of set clause side effects|7",
  "clauses/set > Set6 - Persistence of set clause side effects|8",
  "clauses/set > Set6 - Persistence of set clause side effects|9",
  "clauses/unwind > Unwind1|11",
  "clauses/unwind > Unwind1|12",
  "clauses/unwind > Unwind1|13",
  "clauses/unwind > Unwind1|14",
  "clauses/unwind > Unwind1|3",
  "clauses/unwind > Unwind1|4",
  "clauses/unwind > Unwind1|5",
  "clauses/unwind > Unwind1|6",
  "clauses/unwind > Unwind1|7",
  "clauses/unwind > Unwind1|9",
  "clauses/with > With1 - Forward single variable|2",
  "clauses/with > With1 - Forward single variable|3",
  "clauses/with > With1 - Forward single variable|4",
  "clauses/with > With2 - Forward single expression|1",
  "clauses/with > With2 - Forward single expression|2",
  "clauses/with > With3 - Forward multiple expressions|1",
  "clauses/with > With4 - Variable aliasing|1",
  "clauses/with > With4 - Variable aliasing|6",
  "clauses/with > With4 - Variable aliasing|7",
  "clauses/with > With5 - Implicit grouping with DISTINCT|2",
  "clauses/with > With6 - Implicit grouping with aggregates|1",
  "clauses/with > With6 - Implicit grouping with aggregates|2",
  "clauses/with > With6 - Implicit grouping with aggregates|3",
  "clauses/with > With6 - Implicit grouping with aggregates|4",
  "clauses/with > With6 - Implicit grouping with aggregates|5",
  "clauses/with > With7 - WITH on WITH|1",
  "clauses/with > With7 - WITH on WITH|2",
  "expressions/aggregation > Aggregation1 - Count|1",
  "expressions/aggregation > Aggregation1 - Count|2",
  "expressions/aggregation > Aggregation2 - Min and Max|1",
  "expressions/aggregation > Aggregation2 - Min and Max|10",
  "expressions/aggregation > Aggregation2 - Min and Max|11",
  "expressions/aggregation > Aggregation2 - Min and Max|12",
  "expressions/aggregation > Aggregation2 - Min and Max|2",
  "expressions/aggregation > Aggregation2 - Min and Max|3",
  "expressions/aggregation > Aggregation2 - Min and Max|4",
  "expressions/aggregation > Aggregation2 - Min and Max|5",
  "expressions/aggregation > Aggregation2 - Min and Max|6",
  "expressions/aggregation > Aggregation2 - Min and Max|7",
  "expressions/aggregation > Aggregation2 - Min and Max|8",
  "expressions/aggregation > Aggregation2 - Min and Max|9",
  "expressions/aggregation > Aggregation3 - Sum|1",
  "expressions/aggregation > Aggregation3 - Sum|2",
  "expressions/aggregation > Aggregation5 - Collect|1",
  "expressions/aggregation > Aggregation5 - Collect|2",
  "expressions/aggregation > Aggregation6 - Percentiles|5",
  "expressions/aggregation > Aggregation8 - DISTINCT|1",
  "expressions/aggregation > Aggregation8 - DISTINCT|2",
  "expressions/aggregation > Aggregation8 - DISTINCT|3",
  "expressions/aggregation > Aggregation8 - DISTINCT|4",
]);
